FROM arm64v8/ros:humble

SHELL ["/bin/bash", "-c"]

WORKDIR /ros2_ws

COPY ros2_ws/src ./src

RUN apt-get update && \
    apt-get install -y python3-rosdep && \
    rm -rf /var/lib/apt/lists/*

RUN rosdep init 2>/dev/null || true
RUN rosdep update

RUN source /opt/ros/humble/setup.bash && \
    rosdep install \
        --from-paths src \
        --ignore-src \
        -r \
        -y

RUN source /opt/ros/humble/setup.bash && \
    colcon build

COPY start.sh /start.sh
RUN chmod +x /start.sh

ENTRYPOINT ["/start.sh"]